# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('iic', 'iic'),
        ('iic/SenseVoiceSmall/model.pt', 'iic/SenseVoiceSmall/'),
        ('iic/fsmn-vad/model.pt', 'iic/fsmn-vad/'),
        ('iic/paraformer-zh-streaming/model.pt', 'iic/paraformer-zh-streaming/'),
    ],
    hiddenimports=[
        'PyQt5.QtCore',
        'PyQt5.QtGui', 
        'PyQt5.QtWidgets',
        'numpy',
        'sounddevice',
        'funasr',
        'keyboard',
        'torch',
        'torchaudio', 
        'modelscope',
        'soundfile',
        'librosa',
        'scipy',
        'transformers',
        'onnxruntime',
        'funasr.models',
        'funasr.utils',
        'funasr.datasets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='语音识别工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info_for_build.py',
)
